services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  jyotigpt:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/y4shg/jyotigpt-web:${JYOTIGPT_DOCKER_TAG-main}
    container_name: jyotigpt
    volumes:
      - jyotigpt:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${JYOTIGPT_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'JYOTIGPT_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  jyotigpt: {}
