apiVersion: apps/v1
kind: Deployment
metadata:
  name: jyotigpt-deployment
  namespace: jyotigpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jyotigpt
  template:
    metadata:
      labels:
        app: jyotigpt
    spec:
      containers:
      - name: jyotigpt
        image: ghcr.io/y4shg/jyotigpt-web:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.jyotigpt.svc.cluster.local:11434"
        tty: true
        volumeMounts:
        - name: jyotigpt-volume
          mountPath: /app/backend/data
      volumes:
      - name: jyotigpt-volume
        persistentVolumeClaim:
          claimName: jyotigpt-pvc          